# Generated by Django 3.2 on 2023-12-22 17:00

import Users.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20231126_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models',
            name='file',
            field=models.FileField(upload_to=Users.models.generate_files_dirname, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xmile', 'mdl'])]),
        ),
    ]
