# Generated by Django 3.2 on 2023-12-23 18:47

import Users.models
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_submodels'),
    ]

    operations = [
        migrations.AddField(
            model_name='submodels',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to=Users.models.get_parent_model_dirname, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xmile', 'mdl'])]),
            preserve_default=False,
        ),
    ]
