# Generated by Django 3.2 on 2023-12-26 19:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_submodels_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submodels',
            name='file',
            field=models.FileField(upload_to='models/1/model5/files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xmile', 'mdl'])]),
        ),
    ]
