# Generated by Django 3.2 on 2024-06-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_auto_20240415_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
