version: '3'

services:
  db_users:
    image: postgres:latest
    restart: always
    container_name: postgreDb_users
    hostname: myhost
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./postgre/volumes/Data1:/var/lib/postgresql/data
      - ./postgre/sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - ./postgre/sql/data.sql:/docker-entrypoint-initdb.d/data.sql
    healthcheck:
      test: pg_isready -U postgres
  web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8001:8000"
        depends_on:
            db_users:
              condition: service_healthy
