version: '3'

services:
  db_users:
    image: postgres:latest
    restart: always
    container_name: postgreDb_users
    hostname: db_users
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./postgre/dump-files:/dump-files
    healthcheck:
      test: pg_isready -d db -U admin
    ports:
      - "5432:5432"
  web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8001:8000"
        depends_on:
            db_users:
              condition: service_healthy
